## This is necessary in every program to use Numpy we need to export this first

In [1]:
import numpy as np

Now we are going to make a array using numpy
to do this we will initialize a array as follows

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


This was a one dimentional array 1D there can be multi dimentional array's as shown in the the following types of array's

In [4]:
b = np.array([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]])
## This is a 2 dimentional array
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


Likewise this is a three dimentional array 3D

In [5]:
c = np.array([[[0],[0]],[[0],[0]]])
## This is a three dimentional array a list witin a list within a list 
## Generallly we dont need to visuallize it we we might need to :(
print(c)

[[[0]
  [0]]

 [[0]
  [0]]]


## Now we will use the properties of the nparray
(the functions that come with it)

In [6]:
## This is to get the dimensions of the array
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [7]:
## This is to check the shape of the array
print(a.shape)
## This is a vector as a is a single dimension so it only shows one dimension
print(b.shape)
print(c.shape)
## The orientation this is first rows then column

(10,)
(2, 3)
(2, 2, 1)


In [8]:
## This is to get the data type of the array
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int32


We can also change the datatype of an array by mentioning the datatype in the following way.

In [9]:
d = np.array([1,2,3,4,5], dtype='int16')
print(d.dtype)

int16


So there are two types of size one is item size which is how much each element of the array is taking and 
size of the array is the total number of items present in the array.
So the total size of the array can be calculated as follows x.itensize * x.size (there is also a function that calculates this for us .nbytes)

In [10]:
## This is to get the size of the array (size/memory allocated to these arrays)
print(a.itemsize)
print(a.size)
print(a.size * a.itemsize)
print(a.nbytes)

4
10
40
40


In [11]:
## This is to get the size of the array (size/memory allocated to these arrays)
print(d.itemsize)
print(d.size)
print(d.size * d.itemsize)
print(d.nbytes)

2
5
10
10


## Now we will see how to access or change certain data in a array

In [12]:
##The counting in python works in the following ways

##elements      1   2   3   4   5   6   7   8   9

##counting 1    0   1   2   3   4   5   6   7   8

##counting 2    0  -8  -7  -6  -5  -4  -3  -2  -1

First let's define some new arrays to work on

In [13]:
## Defining a new array 2D array
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(x)
print(x.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


Now we will try to get a specific element from the array 
**To do that we will use the notation of [row, column] [r,c]**
And always remember the counting in Python starts from 0
so if we want to access the 10 which is present in the row 2 column 3 we need to do this

In [14]:
print(x[1,2])

10


We can also use negative annotation to extract elements from the array in the following way if we want to extract 13

In [15]:
print(x[1,-2])

13


Now lets see how to export a entire Row or Column we will use the ":" character for doing this as we have used it simallary in a list

In [16]:
print(x[1,:])
print(x[:,3])
# ':' this characteer meas give the all of the rows or colums in the present vice versa for example (3,:) mans give me all the colums on row number 3
# Dont forget how the counting in pythonn works reffer above

[ 8  9 10 11 12 13 14]
[ 4 11]


There is a way to do a little bit more actually unnder the hood this line works in the following ways

    We can mention the varriable then in the box bracketsits the following **x['the row/column', startindex:endindex:stepsize]**
    Like following 
    The step size means the jump in between the elements

**x['the row/column', startindex:endindex:stepsize]**

In [17]:
x[0, 1:8:2]

array([2, 4, 6])

Now lets see how to change a element

In [18]:
x[0,1] = 9
print(x)

[[ 1  9  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


We can also change entire rows or colums in the following ways

In [19]:
x[1,:] = 22
print(x)

[[ 1  9  3  4  5  6  7]
 [22 22 22 22 22 22 22]]


**Now lets see a 3-D exapmle**

In [20]:
#initialying a 3-d array
y = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Now lets see how to get a specific -element in a 3-D array 


In [21]:
#get a specific element 
#of get or work with complex 3D or bigger arrays we work outside in
#for example we will first define the outer array then we will go into the inner matrices
print ((y[0,1,1]))

4


Now if we have to change some elements it works the same way but if we want to change the a matrices entirely we can do that too but the matrices have to be of the same dimensions 

In [22]:
y[:,1,:] = [[0,0],[0,0]]
print(y)

[[[1 2]
  [0 0]]

 [[5 6]
  [0 0]]]


## Initializing Different Types of Arrays

Now we will see how many different types of array exist and how to initialize those

In [32]:
## All zero matrices can be created in the following ways
zero = np.zeros(3)
zero2 = np.zeros((2,3))
zero3 = np.zeros((2,3,3))

print(zero)
print()
print(zero2)
print()
print(zero3)

[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [36]:
## Now Lets try to make a 1s matriuc
## We can also specify the data type we wa the matrice of like following
one = np.ones((4,2,2), dtype='int32')
print(one)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [43]:
## and to make a matrice of any other number 
other = np.full((2,2), 69, dtype='int64')
## This takes in 2 inputs the shape of the matrice and then the nummber we wanna fill the matrice of
## Here 2,2  is the shape of the matrice and 69 is the number we chose to fill the matrice with.
## We can also put a data type after this as , dtype='int32' 
print (other)

[[69 69]
 [69 69]]


In [52]:
## We can use the shapes of pre existing arrays by using the function full_like
print(y)
print()
_= np.full_like(y,0)
## The above sintax can also be written as np.full(y.shape, 0)
print(_)

[[[1 2]
  [0 0]]

 [[5 6]
  [0 0]]]

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [74]:
## How to make a array with random decimal numbers
print(np.random.rand(4,2,3))

print()
print()

## If we wanna pass in a shape and then fill it wih random nubers the sinntax for that is as follows
print(np.random.random_sample(y.shape))

[[[0.43950941 0.37180757 0.89191986]
  [0.44409529 0.06898492 0.16560001]]

 [[0.84536881 0.93149166 0.44073231]
  [0.06371611 0.42369353 0.19712728]]

 [[0.46182243 0.22317758 0.2246133 ]
  [0.75123274 0.6879029  0.66252754]]

 [[0.72789806 0.89657452 0.72433498]
  [0.98018488 0.63743229 0.85772306]]]


[[[0.77238359 0.56820727]
  [0.59797921 0.7056567 ]]

 [[0.10989279 0.91439554]
  [0.14762193 0.16640352]]]


In [78]:
## How to make a array with random decimal numbers
np.random.randint(5, size=(3,3))
## The first one is the limit (2,4) means the number generated will be a part of 

array([[4, 1, 1],
       [1, 0, 1],
       [0, 3, 1]])