## This is necessary in every program to use Numpy we need to export this first

In [51]:
import numpy as np

Now we are going to make a array using numpy
to do this we will initialize a array as follows

In [52]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [53]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


This was a one dimentional array 1D there can be multi dimentional array's as shown in the the following types of array's

In [54]:
b = np.array([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]])
## This is a 2 dimentional array
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


Likewise this is a three dimentional array 3D

In [55]:
c = np.array([[[0],[0]],[[0],[0]]])
## This is a three dimentional array a list witin a list within a list 
## Generallly we dont need to visuallize it we we might need to :(
print(c)

[[[0]
  [0]]

 [[0]
  [0]]]


## Now we will use the properties of the nparray
(the functions that come with it)

In [56]:
## This is to get the dimensions of the array
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [57]:
## This is to check the shape of the array
print(a.shape)
## This is a vector as a is a single dimension so it only shows one dimension
print(b.shape)
print(c.shape)
## The orientation this is first rows then column

(10,)
(2, 3)
(2, 2, 1)


In [58]:
## This is to get the data type of the array
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int32


We can also change the datatype of an array by mentioning the datatype in the following way.

In [59]:
d = np.array([1,2,3,4,5], dtype='int16')
print(d.dtype)

int16


So there are two types of size one is item size which is how much each element of the array is taking and 
size of the array is the total number of items present in the array.
So the total size of the array can be calculated as follows x.itensize * x.size (there is also a function that calculates this for us .nbytes)

In [60]:
## This is to get the size of the array (size/memory allocated to these arrays)
print(a.itemsize)
print(a.size)
print(a.size * a.itemsize)
## The function nbytes is nothing else but size of one element * no of total elements
print(a.nbytes)

4
10
40
40


In [61]:
## This is to get the size of the array (size/memory allocated to these arrays)
## The function nbytes is nothing else but size of one element * no of total elements
print(d.itemsize)
print(d.size)
print(d.size * d.itemsize)
print(d.nbytes)

2
5
10
10


## Now we will see how to access or change certain data in a array

In [62]:
##The counting in python works in the following ways

##elements      1   2   3   4   5   6   7   8   9

##counting 1    0   1   2   3   4   5   6   7   8

##counting 2    0  -8  -7  -6  -5  -4  -3  -2  -1

First let's define some new arrays to work on

In [63]:
## Defining a new array 2D array
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(x)
print(x.shape)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


Now we will try to get a specific element from the array 
**To do that we will use the notation of [row, column] [r,c]**
And always remember the counting in Python starts from 0
so if we want to access the 10 which is present in the row 2 column 3 we need to do this

In [64]:
print(x[1,2])

10


We can also use negative annotation to extract elements from the array in the following way if we want to extract 13

In [65]:
print(x[1,-2])

13


Now lets see how to export a entire Row or Column we will use the ":" character for doing this as we have used it simallary in a list

In [66]:
print(x[1,:])
print(x[:,3])
# ':' this characteer meas give the all of the rows or colums in the present vice versa for example (3,:) mans give me all the colums on row number 3
# Dont forget how the counting in pythonn works reffer above

[ 8  9 10 11 12 13 14]
[ 4 11]


There is a way to do a little bit more actually unnder the hood this line works in the following ways

    We can mention the varriable then in the box bracketsits the following **x['the row/column', startindex:endindex:stepsize]**
    Like following 
    The step size means the jump in between the elements

**x['the row/column', startindex:endindex:stepsize]**

In [67]:
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [68]:
x[0, 1:8:2]

array([2, 4, 6])

Now lets see how to change a element

In [69]:
x[0,1] = 9
print(x)

[[ 1  9  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


We can also change entire rows or colums in the following ways

In [70]:
x[1,:] = 22
print(x)

[[ 1  9  3  4  5  6  7]
 [22 22 22 22 22 22 22]]


**Now lets see a 3-D exapmle**

In [71]:
#initialying a 3-d array
y = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Now lets see how to get a specific -element in a 3-D array 


In [72]:
#get a specific element 
#of get or work with complex 3D or bigger arrays we work outside in
#for example we will first define the outer array then we will go into the inner matrices
print ((y[0,1,1]))

4


Now if we have to change some elements it works the same way but if we want to change the a matrices entirely we can do that too but the matrices have to be of the same dimensions 

In [73]:
y[:,1,:] = [[0,0],[0,0]]
print(y)

[[[1 2]
  [0 0]]

 [[5 6]
  [0 0]]]


## Initializing Different Types of Arrays

Now we will see how many different types of array exist and how to initialize those

In [74]:
## All zero matrices can be created in the following ways
zero = np.zeros(3)
zero2 = np.zeros((2,3))
zero3 = np.zeros((2,3,3))

print(zero)
print()
print(zero2)
print()
print(zero3)

[0. 0. 0.]

[[0. 0. 0.]
 [0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [75]:
## Now Lets try to make a 1s matriuc
## We can also specify the data type we wa the matrice of like following
one = np.ones((4,2,2), dtype='int32')
print(one)

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [76]:
## and to make a matrice of any other number 
other = np.full((2,2), 69, dtype='int64')
## This takes in 2 inputs the shape of the matrice and then the nummber we wanna fill the matrice of
## Here 2,2  is the shape of the matrice and 69 is the number we chose to fill the matrice with.
## We can also put a data type after this as , dtype='int32' 
print (other)

[[69 69]
 [69 69]]


In [77]:
## We can use the shapes of pre existing arrays by using the function full_like
print(y)
print()
_= np.full_like(y,0)
## The above sintax can also be written as np.full(y.shape, 0)
print(_)

[[[1 2]
  [0 0]]

 [[5 6]
  [0 0]]]

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [78]:
## How to make a array with random decimal numbers
print(np.random.rand(4,2,3))

[[[0.37966012 0.17311389 0.17338978]
  [0.50314538 0.34600566 0.96886809]]

 [[0.77518647 0.19955621 0.11568769]
  [0.05187011 0.29314221 0.87662799]]

 [[0.64056259 0.29742309 0.49464663]
  [0.49165189 0.77537926 0.21528845]]

 [[0.82408785 0.41462216 0.07491978]
  [0.03122379 0.63077466 0.82565516]]]


In [79]:
## If we wanna pass in a shape and then fill it wih random nubers the sinntax for that is as follows
print(np.random.random_sample(y.shape))
## we can use any shape not necessarily y.shape

[[[0.36573613 0.38332433]
  [0.32402865 0.05930611]]

 [[0.17501393 0.42562513]
  [0.72866809 0.87062071]]]


In [80]:
## How to make a array with random decimal numbers
np.random.randint(2,10, size=(3,3))
## The first one is the limit (2,10) means the number generated will be in between 2 and 10 (can also go negative) 

array([[9, 6, 9],
       [5, 4, 4],
       [9, 8, 8]])

In [81]:
## This is how to make a identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [82]:
## How to repeat an array
rep = np.array([[1,2,3]])
r1 = np.repeat(rep ,3 , axis=0)
print(r1)
## The Axis make the array repeat horizontally or vertically repeat itself
r2 = np.repeat(rep ,3 , axis=1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


Now try initializing the following array.

1 1 1 1 1

1 0 0 0 1

1 0 9 0 1

1 0 0 0 1

1 1 1 1 1

In [83]:
sol = np.ones((5,5))

mid =  np.zeros((3,3))
mid[1,1] = 9

sol [1:4, 1:4] = mid
print(sol)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [84]:
##Do aware while coppying an array
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)
print(b)

[100   2   3]
[100   2   3]


In [85]:
## To avoide this we use the copy function as follows

a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathametics

In [86]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [87]:
a+=2
a

array([3, 4, 5, 6])

In [88]:
a-2

array([1, 2, 3, 4])

In [89]:
a*2

array([ 6,  8, 10, 12])

In [90]:
a/2

array([1.5, 2. , 2.5, 3. ])

In [91]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [92]:
a ** 2

array([ 1,  4,  9, 16])

In [93]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Liner Aljebra

In [94]:
a= np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

#### Finding the Determinant

In [95]:
c = np.identity(3)
np.linalg.det(c)
## This is the syntax for finding the determinant for a matrice
 
### We can do other Linear algebra calculations on matrices using numpy library such as the following
## Determinant
## Trace
## Singular vector Decomposition
## Inverse Matrices
## ETC

1.0

#### Statistics

In [96]:
stats_1 = np.array([[1,2,3],[4,5,6]])
stats_1

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
##This prints the min value of the entre matrice
print(np.min(stats_1))
## Now we can get a bit fancy with it we can specify a row or column or row and column in general which's element is the smallest 
np.min(stats_1, axis=1)

1


array([1, 4])

In [98]:
## Similar to min this goes for max as well as shown in the following.
print(np.max(stats_1))
np.max(stats_1, axis=1)

6


array([3, 6])

In [99]:
## We can sum up all the elements in the matrix by using the np.sum function
print(np.sum(stats_1))
## Same here we can aslo specify axis as per needs

21


#### Reorganizing arrays

In [100]:
beffore = np.array([[1,2,3,4],[5,6,7,8]])
print (beffore)
print (beffore.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [106]:
## If we want to change the shape we can do it like
after = beffore.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [109]:
after2 = beffore.reshape((2,2,2))
print(after2)
## We can do any shape till we have the same elements

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [119]:
## Now look at vertically stacking matrices
p1 = np.array([1,2,3,4,5])
p2 = np.array([6,7,8,9,10])

p3 = np.vstack([p1,p2])
print(p3)

## We can keep passing this in for example
_ = np.vstack([p1,p2,p1,p1])
print(_)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 1  2  3  4  5]]


In [120]:
## Now look at horrizintally stacking matrices
p4 = np.hstack([p1,p2])
print(p4)

[ 1  2  3  4  5  6  7  8  9 10]


In [121]:
## The end for now i need to look into boolean masking and stuff

In [ ]:
## TBD